// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omdigsjxzjyeoleeqmnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tZGlnc2p4emp5ZW9sZWVxbW54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MjY0NTksImV4cCI6MjA3NDUwMjQ1OX0.OuvGSc2xZeJwcSdgt_MuHh4P90NV2-RMPyQrBx7b0kQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});